server {
    listen 8080;
    server_name _;

    root /app/public;
    index index.html;

    access_log /dev/stdout;
    error_log /dev/stderr;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~* \.(?:css|jpg|jpeg|png|gif|ico)$ {
        expires 1h;
        add_header Cache-Control "public";
    }
}
